### ISSUE TITLE
Blank window on Windows 7

### ISSUE THREAD

**Issue by kolqw1** [ZcashFoundation/zecwallet#250] opened 2020-03-14 15:57 UTC
Can't see UI on Windows 7 64 bit Version 6.1 Build 7600. Tested for Zecwallet v0.9.5. A screenshot is attached.
![image](https://user-images.githubusercontent.com/62180008/76685450-5cc8c380-661c-11ea-826e-b3fab0b9866b.png)

I couldn't select the "Bug report" option. I think, because of some problems with the template.

**Comment by adityapk00** [comment] 2020-03-15 16:20
I can't seem to reproduce this problem. Can you help me with more details?

- Did you download the `.msi` or the `.zip`?
- Are you running an external zcashd?
- Do you have a previous version of zecwallet installed?

**Comment by kolqw1** [comment] 2020-03-17 11:35
* I downloaded `.zip`
* I am running the embedded zcashd. I think, that zcashd works well. I can see zcahd in windows task manager and it seems, that synchronization works.
* I have several previous versions of zecwallet, but they are all `.zip` versions. I'm using Zecwallet v0.8.3 now.

I think the problem is only with UI. Maybe because the operating system is outdated (it's even not SP1). Perhaps some libraries are missing. I can see UI on another computer with Windows 10.

**Comment by adityapk00** [comment] 2020-03-17 16:42
I'm going to close this issue as wont fix, because of the old version of windows you are using seems to be missing some libraries. Win 7 won't be supported, sorry.

**Closed by adityapk00** 2020-03-17 16:42 UTC
