### ISSUE TITLE
hell

### ISSUE THREAD

**Issue by set34342** [ZcashFoundation/zecwallet#273] opened 2020-07-17 04:02 UTC
during the transfer of coins to me, the wallet lost contact. I can’t get coins.

**Comment by adityapk00** [comment] 2020-07-17 04:15
Please see the troubleshooting section for syncing issues: https://docs.zecwallet.co/troubleshooting/#my-node-isnt-syncing

Also, please make sure you have the latest version of Zecwallet

**Comment by adityapk00** [comment] 2020-07-17 04:15
Duplicate of #271

**Closed by adityapk00** 2020-07-17 04:15 UTC
Labels: enhancement

**Comment by adityapk00** [comment] 2020-07-18 01:20
https://github.com/zcash/zcash/issues/4620

**Comment by adityapk00** [comment] 2020-07-24 17:45
There's now a new version of Zecwallet (v0.9.15) that works around this problem on Windows. Please see the release here: https://github.com/ZcashFoundation/zecwallet/releases/tag/v0.9.15
