### ISSUE TITLE
headless errors

### ISSUE THREAD

**Issue by buzon7** [ZcashFoundation/zecwallet#114] opened 2019-03-06 10:13 UTC
Thanks for headless release! However, on my Debian 8.11 getting two errors:
~$ zec-qt-wallet --headless
zec-qt-wallet: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by zec-qt-wallet)

zec-qt-wallet: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by zec-qt-wallet)

My libstdc++6 strings versions are 3.4.20 and 1.3.8 respectively. Any ideas how to upgrade it? 

Also, how do I get a connection string for android once zec-qt-wallet starts headless?

**Comment by adityapk00** [comment] 2019-03-06 22:00
I think the minimum supported version of debian for the builds is debian 9. To get it work on Debian 8.1, you might have to compile yourself. 

See here: https://docs.zecqtwallet.com/compile-from-source/

**Comment by buzon7** [comment] 2019-03-08 20:03
Thanks, I tried, but am getting error "cannot find ui_mobileappconnector.h in mainwindows.cpp and websockets.h". The previous master and websocket branches were compiling fine.

And what about the second question: how to get the connection string without UI?

**Comment by adityapk00** [comment] 2019-03-11 04:21
The `ui_*.h` files are generated by the build process automatically. Did you run the `qmake` command before the build? If you did, can you tell me what version of Qt you have installed?

The headless mode right now is kind of limited. You need to run it with the UI the first time, to set up configuration, get the connection string etc..., and subsequently you can run it in a headless mode in a systemd service etc...

If there's enough interest in the community, I can try and build a completely headless version that does the connection string etc... on the command line itself.

**Comment by buzon7** [comment] 2019-03-11 10:13
Hi, thanks for replying! I don't remember how I did it, but previously I could build both master and websocket branches from within Qt Creator. In VS command prompt my Qt\5.12.1\msvc2017\bin\qmake runs fine (creating stash file), but I get these errors in the end of nmake:

Generating Code...
        link /NOLOGO /DYNAMICBASE /NXCOMPAT /DEBUG /SUBSYSTEM:WINDOWS "/MANIFESTDEPENDENCY:type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' publicKeyToken='6595b64144ccf1df' language='*' processorArchitecture='*'" /MANIFEST:embed /OUT:debug\zec-qt-wallet.exe @C:\Users\[...]\AppData\Local\Temp\nm4065.tmp
main.obj : error LNK2019: unresolved external symbol _sodium_init referenced in function "public: int __thiscall Application::main(int,char * * const)" (?main@Application@@QAEHHQAPAD@Z)
websockets.obj : error LNK2019: unresolved external symbol _crypto_hash_sha256 referenced in function "public: class QString __thiscall AppDataServer::getWormholeCode(class QString)" (?getWormholeCode@AppDataServer@@QAE?AVQString@@V2@@Z)
websockets.obj : error LNK2019: unresolved external symbol _crypto_secretbox_easy referenced in function "public: class QString __thiscall AppDataServer::encryptOutgoing(class QString)" (?encryptOutgoing@AppDataServer@@QAE?AVQString@@V2@@Z)websockets.obj : error LNK2019: unresolved external symbol _crypto_secretbox_open_easy referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
websockets.obj : error LNK2019: unresolved external symbol _randombytes_buf referenced in function "public: void __thiscall AppDataServer::updateUIWithNewQRCode(class MainWindow *)" (?updateUIWithNewQRCode@AppDataServer@@QAEXPAVMainWindow@@@Z)
websockets.obj : error LNK2019: unresolved external symbol _sodium_memzero referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
websockets.obj : error LNK2019: unresolved external symbol _sodium_compare referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
websockets.obj : error LNK2019: unresolved external symbol _sodium_increment referenced in function "public: class QString __thiscall AppDataServer::encryptOutgoing(class QString)" (?encryptOutgoing@AppDataServer@@QAE?AVQString@@V2@@Z)
websockets.obj : error LNK2019: unresolved external symbol _sodium_bin2hex referenced in function "public: void __thiscall AppDataServer::updateUIWithNewQRCode(class MainWindow *)" (?updateUIWithNewQRCode@AppDataServer@@QAEXPAVMainWindow@@@Z)
websockets.obj : error LNK2019: unresolved external symbol _sodium_hex2bin referenced in function "public: class QString __thiscall AppDataServer::decryptMessage(class QJsonDocument,class QString,class QString)" (?decryptMessage@AppDataServer@@QAE?AVQString@@VQJsonDocument@@V2@1@Z)
D:\DevOps\zec-qt-wallet\res\libsodiumd.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
debug\zec-qt-wallet.exe : fatal error LNK1120: 10 unresolved externals
NMAKE : fatal error U1077: '"d:\DevOps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\link.EXE"' : return code '0x460'
Stop.
NMAKE : fatal error U1077: '"d:\DevOps\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

If I try to build it in Qt Creator, a different issue appears:
:-1: error: dependent 'qrcodelabel.h' does not exist. (but the file does exist in src)

I still have v0.5.9 android beta project that builds and runs fine, so not really sure what I am doing wrong with master branch.

I still have no plan how to build a linux version though - Qt is not easy to install on a headless server ((( Is there a kit to build a Debian 8 version from Windows?

**Comment by buzon7** [comment] 2019-03-11 10:40
Ah, ok, I remembered what I did last time. I compiled x86 version of libsodium. Now zec-qt-wallet builds on Windows ok. Now need to learn to buld it for Debian 8 ))

**Comment by adityapk00** [comment] 2019-03-11 19:10
Glad you build the x86 version, just know that it's not really officially supported. I'd recommend you use the x64 bit versions :) 

Anyway, installing and building Qt on a headless server is somewhat harder, but I've documented it here: 
https://github.com/ZcashFoundation/zec-qt-wallet/wiki/Setting-up-a-build-environment

Look under the `static build of Qt5` section

**Comment by buzon7** [comment] 2019-03-12 10:04
Ok, will give it a try, thanks! Always glad to learn something new.

**Comment by buzon7** [comment] 2019-03-13 08:21
Nope. Headless Debian is no go to build Qt: getting bunch of errors about fonts and then make fails. Any other modules I can add to -skip to avoid that?

**Comment by adityapk00** [comment] 2019-03-13 21:29
Hmm.. I think there's a way to install a "null" framebuffer to get it to compile, but I haven't tried it yet. Let me spend some time investigating. 

Meanwhile, if you can compile on a UI machine and copy over the binaries, that might be worth trying too .

**Comment by adityapk00** [comment] 2019-07-24 17:48
Duplicate of #127

**Closed by adityapk00** 2019-07-24 17:48 UTC
Labels: enhancement
